services:

  piper:
    build: .
    container_name: piper-tts

    ports:
      - "5060:5000"

    devices:
      - /dev/snd:/dev/snd

    volumes:
      - ./voices:/voices:z

    environment:
      PIPER_MODEL: /voices/en_GB-semaine-medium.onnx
      AUDIO_DEVICE: "plughw:3,0"
      SPEECH_SPEED: 0.85

    restart: unless-stopped
